# Configure the Repo Lockdown GitHub App to automatically close pull requests.
# See https://github.com/dessant/repo-lockdown

name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened
  schedule:
    - cron: '7 * * * *'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          pr-comment: >
            Hi, thank you for your contribution!

            GitHub is however not the right place for these. The development repository is
            hosted on GitLab: <https://gitlab.com/wireshark/wireshark>. Please have a look at
            <https://www.wireshark.org/docs/wsdg_html_chunked/ChSrcContribute.html>
            for further instructions.
